#!/bin/bash

set -e

INSTALL_PATH=@CPACK_PACKAGING_INSTALL_PREFIX@

do_ldconfig() {
  echo ${INSTALL_PATH}/lib > /etc/ld.so.conf.d/10-rocm-opencl.conf && ldconfig
  mkdir -p /etc/OpenCL/vendors && (echo libamdocl64.so > /etc/OpenCL/vendors/@OPENCL_AMD_ICD_FILE@)
}

case "$1" in
  abort-deconfigure|abort-remove|abort-upgrade)
    echo "$1"
  ;;
  configure)
    do_ldconfig
  ;;
  *)
    exit 0
  ;;
esac
